version: '3.8'  # It's good practice to specify the version

services:
  ecommerce:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    networks:
      - my_network
    volumes:
      - ./app:/code # Changed from ./app:/code to .:/code
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
